use_frameworks!

target 'SwiftyAnalytics_Example' do
  pod 'SwiftyAnalytics/Firebase', :path => '../'
  pod 'SwiftyAnalytics/Facebook', :path => '../'
  pod 'SwiftyAnalytics/Tenjin', :path => '../'

  target 'SwiftyAnalytics_Tests' do
    inherit! :search_paths

    
  end
end
